# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
includes_dir: includes

# JF: I have to do this so that SASS files are served properly while in "jekyll serve" mode. It's silly.
include:
  - _base.scss
  - _container.scss
  - _fonts.scss
  - _hello.txt
  - _helpers.scss
  - _ie.scss
  - _layout.scss
  - _variables.scss
  - _all.scss
  - _classes-social.scss
  - _classes.scss
  - _functions.scss
  - _variables-theme.scss
  - _variables-unicode-social.scss
  - _variables-unicode.scss
  - _infobox.scss
  - _helpers.scss
  - _reset.scss
  - _responsive-variables.scss
  - _all.scss
  - _mixins.scss
  - _variables.scss
  - _o-form-variable.scss
  - _o-form.scss
  - _accessibility.scss
  - _app-login-banner.scss
  - _beacon.scss
  - _btns.scss
  - _consent.scss
  - _enroll.scss
  - _factors-dropdown.scss
  - _footer.scss
  - _forgot-password.scss
  - _forms.scss
  - _header.scss
  - _infobox.scss
  - _mfa-challenge-forms.scss
  - _okta-footer.scss
  - _qtip.scss
  - _registration.scss
  - _social.scss
  - _chosen.scss
  - _jquery.qtip.scss
  - _mega-drop-down.scss
exclude:
  - Gemfile
  - Gemfile.lock
